version: 2.1
parameters:
  is_pr:
    type: boolean
    default: false
jobs:
  test_main_flow:
    docker:
      - image: hoanito/mbr-ubuntu:1.1
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run: mkdir -p /massbitroute/nodetest && cd /massbitroute/nodetest
      - checkout
      - run: 
          name: Obtain GCE key
          command: echo $PROJECT_KEY > project_key.json
      - run: 
          name: Test main flow for ETH nodes/GW
          command: cd scripts/single-node-test && sudo bash ./single-node-test.sh eth
      - run: 
          name: Test main flow for ETH nodes/GW
          command: cd scripts/single-node-test && sudo bash ./single-node-test.sh dot

# Orchestrate our job run sequence
workflows:
  version: 2

  massbitroute-ci-dev:
    jobs:
      - test_main_flow:
          filters:
            branches:
              only: master

