#!/bin/bash
declare -i DEBUG=0
ROOT_DIR=$(cd "$(dirname $0)" && pwd)
source $ROOT_DIR/bin/shell_func.sh

case "$1" in
install_libs)
	apt install -y libmaxminddb-dev uuid-dev
	for p in luafilesystem lpeg lua-messagepack; do
		/usr/local/openresty/luajit/bin/luarocks install $p
	done
	exit 0
	;;
_update)
	updateConfigs
	$ROOT_DIR/bin/openresty/nginx/sbin/nginx -c $ROOT_DIR/tmp/nginx.conf -s reload
	exit 0
	;;
redis)
	shift
	$ROOT_DIR/bin/redis/bin/redis-cli -s $ROOT_DIR/tmp/redis.sock $@
	exit 0
	;;
nginx)
	shift
	$ROOT_DIR/bin/openresty/nginx/sbin/nginx -c $ROOT_DIR/tmp/nginx.conf $@
	exit $?
	;;
esac
updateConfigs
$ROOT_DIR/bin/python_env/gbc/bin/supervisorctl -c $ROOT_DIR/tmp/supervisord.conf $@
