#!/bin/bash
SITE_ROOT=$(realpath $(dirname $(realpath $0))/..)
cd $SITE_ROOT
export HOME=/massbit/massbitroute/app/src/tmp
export ASDF=/massbit/massbitroute/app/src/bin/.asdf/installs
GRAFANA_VERSION=v8.2.1
PROMETHEUS_VERSION=v2.30.3
portal_dir=/massbit/massbitroute/app/src/sites/portal
gwman_dir=/massbit/massbitroute/app/src/sites/services/gwman
gw_dir=/massbit/massbitroute/app/src/sites/services/gateway
cmd_server=/massbit/massbitroute/app/src/cmd_server
gdnsd="/massbit/massbitroute/app/gbc/bin/.asdf/installs/gdnsd/v3.8.0/sbin/gdnsd -c $gwman_dir"
nginx="/massbit/massbitroute/app/src/bin/openresty/nginx/sbin/nginx -c /massbit/massbitroute/app/src/tmp/nginx.conf"

_supervisor() {
	cat <<EOF >/etc/supervisor/conf.d/mbr_portal.conf
[program:mbr_portal]
command=/massbit/massbitroute/app/src/start_server
EOF
}

_git_config() {
	_dir=$1
	if [ -z "$_dir" ]; then _dir=$PWD; fi
	git -C $_dir config --global user.name "Vu Tran"
	git -C $_dir config --global user.email "baysao@gmail.com"
}
_reload() {
	$cmd_server _update
	$cmd_server update
	$cmd_server status | grep worker-portal-api | awk '{print $1}' | while read f; do
		$cmd_server restart $f
	done
}

_git_cmd_commit() {
	_cdir=$1
	shift
	if [ $# -gt 0 ]; then
		_time=$(date -u)
		_git_config $_cdir
		for _fdir in $@; do
			git -C $_cdir add -f $_fdir
		done
		git -C $_cdir commit -m "$_fdir at $_time"

	fi
}

_git_cmd() {
	cmd=$1
	shift
	if [ -z "$cmd" ]; then cmd=push; fi

	_dir_def=/massbit/massbitroute/app/src/sites/services
	for _service in portal gateway node gwman stat monitor; do
		if [ "$_service" = "portal" ]; then
			_dir=/massbit/massbitroute/app/src/sites/portal
		else
			_dir="$_dir_def/$_service"
		fi

		if [ "$cmd" = "commit" ]; then
			_mydir=""
			case "$_service" in
			portal)
				_mydir="$_dir/public/deploy"
				;;
			gwman)
				_mydir="$_dir/data $_dir/zones"
				;;
			stat)
				_mydir="$_dir/etc/prometheus"
				;;
			esac

			if [ -n "$_mydir" ]; then
				_git_cmd_commit $_dir $_mydir
			fi
		else
			git -C $_dir $cmd
		fi
	done

}
_monitor() {
	_git_cmd pull
	reload=0

	if [ ! -d "$SITE_ROOT/vars" ]; then mkdir -p $SITE_ROOT/vars; fi
	echo mbr-portal >$SITE_ROOT/vars/TYPE

	stat_dir=$SITE_ROOT/etc
	if [ ! -d "$stat_dir/mkagent/.git" ]; then
		mkdir -p $stat_dir
		git clone http://mbr_gateway:6a796299bb72357770735a79019612af228586e7@git.massbitroute.com/massbitroute/mkagent.git $stat_dir/mkagent
		is_reload=1
	fi

	for d in /massbit/massbitroute/app/gbc \
		/massbit/massbitroute/app/src \
		$portal_dir \
		$stat_dir/mkagent; do
		git -C $d pull | grep -i "updating"
		if [ $? -eq 0 ]; then
			reload=1
		fi
	done

	if [ $reload -eq 1 ]; then
		$0 _reload
	fi

	_git_cmd commit
	_git_cmd push
}
loop() {
	while true; do
		$0 $@
		sleep 1
	done

}
$@
