{
 "title": "sitestat",
 "description": "Site stats",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "label_values(nginx_vts_filter_requests_total, instance)"
   },
   {
    "name": "Filter",
    "query": "label_values(nginx_vts_filter_requests_total{instance=~\"$Instance\"}, filter)"
   },
   {
    "name": "FilterName",
    "query": "label_values(nginx_vts_filter_requests_total{instance=~\"$Instance\", filter=~\"${Filter:raw}\"}, filter_name)"
   },
   {
    "name": "Upstream",
    "query": "label_values(nginx_vts_filter_requests_total{instance=~\"$Instance\"}, upstream)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_vts_filter_requests_total{filter=\"${Filter:raw}\",filter_name=\"$FilterName\",direction=\"total\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_filter_requests_total{filter=\"${Filter:raw}\",filter_name=\"$FilterName\",direction=\"total\"}[5m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_vts_filter_bytes_total{filter=\"${Filter:raw}\",filter_name=\"$FilterName\", direction=\"out\"})",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_filter_bytes_total{filter=\"${Filter:raw}\",filter_name=\"$FilterName\", direction=\"out\"}[5m])) ",
     "legendFormat": "{{ direction }}"
    }
   ]
  }
 ]
}